# Generated by Django 3.1 on 2021-07-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0002_auto_20210709_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donor_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
