# Generated by Django 3.1 on 2021-07-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentGateway', '0003_donate_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='donor_id',
            field=models.CharField(max_length=100),
        ),
    ]
